### ISSUE TITLE
[Suggestion] Woodcutter

### ISSUE THREAD

**Issue by accessdenied0** [UniversalLP/VanillaAutomation#1]
Hey @UniversalLP ,

I really like the feature with the Dispenser to break some block, but I noticed it doesn't work on Logs.
Can you actually do that Dispensers can break Logs with Axes as tool? That would be a neat feature...

You might already think about it but I ask for it here anyway,

access_denied

**Comment by univrsal** [comment]
Oh, thanks for pointing that out.
I'll definetely look into that, and when I'm at it also add it for shovels.

**Comment by univrsal** [comment]
Should work now in 1.2 (You can grab it from [here](http://minecraft.curseforge.com/projects/vanillaautomation/files). When curse approves the file).
