### ISSUE TITLE
Bug: dispenser can't break modded blocks

### ISSUE THREAD

**Issue by darklordwonton** [UniversalLP/VanillaAutomation#10]
The dispenser doesn't seem to be able to break blocks added by mods when supplied with a tool

**Comment by univrsal** [comment]
What tool and what block?
Is the tool capable of breaking the block in survival by a normal player?

**Comment by darklordwonton** [comment]
I tried with a diamond pickaxe on amethyst blocks from elements of power (which works if a player does it) and an iron chest also a diamond axe on ie crates and forestry wood.

**Comment by univrsal** [comment]
I redid the block breaking method. Should work now with the next release
