### ISSUE TITLE
Suggestions and a problem

### ISSUE THREAD

**Issue by nizarnizario** [UniversalLP/VanillaAutomation#11]
Hi , i already left these comments on the curse page so , i just want to repeat them here so you can see them :) : 
" Great MOD! But the problem is the trading block is crashing the game ; i hope you fix it soon :)"

""And a suggestion , new blocks :
* Auto Crafter (i think it's necessairy for automation)

* Something like vacuum hopper from open blocks , where you collect items in a 3x3 area... ""

**Comment by univrsal** [comment]
Yeah I know about the auto trader I just haven't come around to finishing it :P
As for your two suggestions,  I'll see when I get the time to look at them

**Comment by nizarnizario** [comment]
Good Luck :)
