### ISSUE TITLE
NPE Dispenser

### ISSUE THREAD

**Issue by RainbowSaber** [UniversalLP/VanillaAutomation#12]
Using axes in a dispenser causes the game to crash and doesnt let you load the world until you remove either VanillaAutomation or [TreeChopper](https://minecraft.curseforge.com/projects/tree-chopper).

[FML Crash Report](https://minecraft.curseforge.com/projects/tree-chopper)

Compatibility between those would be much appreciated.

**Comment by RainbowSaber** [comment]
[OpenHarvest](https://minecraft.curseforge.com/projects/openharvest?gameCategorySlug=mc-mods&projectID=246283) works perfectly fine. Ill post this bug to the TreeChopper Thread aswell, since it seems to be a messy implementation on his part

**Comment by univrsal** [comment]
Your crash-report points to the curseforge site of TreeChopper :P

**Comment by RainbowSaber** [comment]
copying links is hard work

[CrashLog](http://pastebin.com/ezntBN9d)

**Comment by univrsal** [comment]
Well I looked into this, and it seems like that's an error on TreeChoppers side.
I'm just calling a vanilla method for block breaking. TreeChopper seems to not check if the block break event variables are null.
