### ISSUE TITLE
[1.12-1.0] [not sure if bug or intended function] Block-breaking dispenser applies extra damage to tools

### ISSUE THREAD

**Issue by zontargs** [UniversalLP/VanillaAutomation#16]
I'm not sure if this is a balance feature or not, but:

-Whenever a tool is used to break a block, 1 damage is applied to the tool, even if breaking by a player would not have damaged the tool.
-If the tool would have taken damage if used by a player, another point of damage is applied.

**Comment by univrsal** [comment]
Seems like Minecraft now damages items automatically so the second damage was done by VA.
It should be fixed now
