### ISSUE TITLE
[1.12-1.0] Dispenser Tweaks ignore the dispenserReach setting

### ISSUE THREAD

**Issue by zontargs** [UniversalLP/VanillaAutomation#17]
Dispensers only attempt to operate on the block immediately in front of the dispenser, regardless of the dispenserReach setting.

**Comment by univrsal** [comment]
The config option only sets the maximum range of the dispenser tweaks. To change the range of the action the dispenser does you'll have to rename the tool.
If you want the dispenser to dig with a shovel three blocks aways you'll need to name the tool "Range: 3"

**Comment by zontargs** [comment]
Ah, OK, thanks!
