### ISSUE TITLE
[1.12] Stick in a dispenser won't close chest or skulker box

### ISSUE THREAD

**Issue by Snownee** [UniversalLP/VanillaAutomation#18]

**Comment by Snownee** [comment]
As a similar issue, stick in a dispenser cannot convert Daylight Sensor twice.

**Comment by univrsal** [comment]
Okay, the dispenser now cannot open chests anymore.
Also the Daylight Sensor issue is because the Daylight Sensor is powering the Dispenser.
Just place the Daylight Sensor one block away and name the Stick "Range: 2"
