### ISSUE TITLE
[1.12] Stick in a dispenser can right-click bed and get the advancement

### ISSUE THREAD

**Issue by Snownee** [UniversalLP/VanillaAutomation#19]

**Comment by univrsal** [comment]
I'm not sure what you mean by 'advancement', but using the dispenser with a stick on a bed will not set the time to day.

**Comment by Snownee** [comment]
Advancements (in 1.12) are similar to achievements, by doing this it will notice all players a FakePlayer has earn a new 'advancement'.

**Comment by univrsal** [comment]
Oh, I guess it shows that I haven't played the game in a while
I added a dummy Advancement class which should prevent the messages from showing up, but I couldn't test it since I don't know what is needed to unlock the bed advancement
EDIT: I didn't get any response so I'll just close this for now
