### ISSUE TITLE
sweeping edge

### ISSUE THREAD

**Issue by TheGuyFromTheInternet** [UniversalLP/VanillaAutomation#25]
Since we can attack multiple mobs at once using a sword, I was wondering if that can be a feature added to the dispenser IF the sword has sweeping edge. It will be able to handle high volume spawning mob/xp farms like the enderman mob farm.

**Comment by univrsal** [comment]
Sorry for the late response, but I don't think I'm going to implement this. The entity attacking is pretty hacky already so I'd like to leave it as it is for now
