### ISSUE TITLE
[1.10] Redstone Clock creates desync in world interaction

### ISSUE THREAD

**Issue by WesCook** [UniversalLP/VanillaAutomation#26]
Hi universal,

First off, I'm a big fan of the mod.  The redstone clock in particular is quite intuitive, and I appreciate that it doesn't carry the bloat of other larger tech mods.

I'm reporting an issue from the latest 1.10.2 build.  I hope that's acceptable, if you're still providing bug fixes for that version.  If not, I understand.  However it's also possible this behavior is still present in newer versions.

The issue is tough to explain, but the clock seems to cause desync issues when in close proximity to it.

This was first reported to me for my modpack here, and it gives an example of the bug.
https://github.com/WesCook/Homestead/issues/42

Unfortunately it's a hard issue to pin down, and the behavior often disappears once you identify it.

Thanks for your time.

**Comment by univrsal** [comment]
I think I fixed that issue in 1.12 at some point so I'll see if I can backport it.

**Comment by WesCook** [comment]
That would be wonderful.  Thank you very much!

**Comment by univrsal** [comment]
So I backported that fix which should prevent the desyncing from happening although I disabled compatibility with other mods (I hope you weren't too fond of JEI/TCon/BoP integration).
The build is up on curseforge so you can test it out.

**Comment by WesCook** [comment]
Great, thanks!  I'm currently in the middle of a PC reformat, but I will be able to test it shortly.  Looks like the build is still queued for approval on Curseforge anyway.

Losing overlay support is no biggie.  I know it's a pain to manage dependency support across versions.

**Comment by WesCook** [comment]
Sorry for the delay on this one.  Changing operating systems and getting back up to speed took a lot longer than I was expecting.

**Comment by univrsal** [comment]
No problem, just tell me if it breaks again :P

**Comment by WesCook** [comment]
I've had a chance to test it out now and it seems to be working great.  Much thanks for backporting the fix.  If I get any more reports of issues I'll let you know.

Small sidenote though.  The filename on Curse does seem to have an error.  The version is `1.10.2-1.7` but the filename is `va-1.10.2-1.6.jar`.  May lead to some confusion down the road.

Cheers.

**Comment by univrsal** [comment]
Oops, fixed now. 
That's what happens when you keep track of the versions manually...
