### ISSUE TITLE
The "Tweaks for the dispenser" section in guide shows a "Format error: "

### ISSUE THREAD

**Issue by Snownee** [UniversalLP/VanillaAutomation#29]
![image](https://user-images.githubusercontent.com/16059084/34090658-8f285578-e3f3-11e7-83a8-2b1cecb78638.png)

**Comment by univrsal** [comment]
I think it's the "5%" that makes minecraft think that I want to format something. I'll take a look at it

**Comment by Snownee** [comment]
Seems that use "5%%" instead can fix this problem

**Comment by univrsal** [comment]
thanks, I didn't know that. Should be fixed now
