### ISSUE TITLE
Current 1.10.2 version calling client code on dedicated server

### ISSUE THREAD

**Issue by maxhenkes** [UniversalLP/VanillaAutomation#3]
Heya,

seems like your latest version is calling client sided code where it shouldn't, getting the following on my dedicated server (singleplayer works, obviously :) )

> Time: 8/11/16 11:27 PM
> Description: Exception in server tick loop
> 
> net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/multiplayer/WorldClient
>   at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:186)
>   at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:776)
>   at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107)
>   at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:333)
>   at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:214)
>   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
>   at java.lang.Thread.run(Thread.java:745)
> Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/multiplayer/WorldClient
>   at java.lang.Class.getDeclaredConstructors0(Native Method)
>   at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
>   at java.lang.Class.getConstructor0(Class.java:3075)
>   at java.lang.Class.newInstance(Class.java:412)
>   at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.instantiate(SimpleNetworkWrapper.java:166)
>   at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.registerMessage(SimpleNetworkWrapper.java:159)
>   at de.universallp.va.core.network.PacketHandler.register(PacketHandler.java:31)
>   at de.universallp.va.core.CommonProxy.init(CommonProxy.java:44)
>   at de.universallp.va.VanillaAutomation.init(VanillaAutomation.java:33)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:498)
>   at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:577)
>   at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:498)
>   at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
>   at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
>   at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
>   at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
>   at com.google.common.eventbus.EventBus.post(EventBus.java:275)
>   at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:235)
>   at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:213)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:498)
>   at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
>   at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
>   at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
>   at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
>   at com.google.common.eventbus.EventBus.post(EventBus.java:275)
>   at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
>   at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:774)
>   ... 5 more
> Caused by: java.lang.ClassNotFoundException: net.minecraft.client.multiplayer.WorldClient
>   at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
>   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
>   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
>   ... 40 more
> Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@7f36662c from coremod FMLCorePlugin
>   at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:253)
>   at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
>   at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
>   ... 42 more
> Caused by: java.lang.RuntimeException: Attempted to load class bln for invalid side SERVER
>   at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:56)
>   at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:249)
>   ... 44 more

**Comment by univrsal** [comment]
Uhh, darn I left some stuff from the unfinished block in there whoops

**Comment by univrsal** [comment]
Alright build is up and I tested it on local server without any issues.
