### ISSUE TITLE
1.12.2 - Cakes Disappear When Placed with Block Placer

### ISSUE THREAD

**Issue by scottosx** [UniversalLP/VanillaAutomation#31]
Vanilla cakes make the sound of placement and are removed from the Block Placer inventory but do not show up in the world. Are gone forever. Cakes from Pam's Harvestcraft do work.

**Comment by univrsal** [comment]
Sorry for not responding on this for so long but I haven't touched minecraft in quite a while.
It's fixed now and I'll release a new version very soon.
Thanks for reporting the issue
