### ISSUE TITLE
Dispenser not immovable 

### ISSUE THREAD

**Issue by Landstryder** [UniversalLP/VanillaAutomation#33]
Not sure if it's a bug or a feature, but dispensers get picked up and moved by slime blocks which breaks some redstone contraptions. Default behaviour is to be immovable like a furnace block. I feel like it must be a bug because they also change the facing direction when that happens.

**Comment by univrsal** [comment]
Like Minecraft Vanilla dispensers? I don't remember applying any changes to them so I'm not sure if this is my mod causing this.

**Comment by Landstryder** [comment]
Yes nevermind, it turns out Quark was adding that "feature" in, sorry.
