### ISSUE TITLE
Redstone clocks don't save the delay ticks.

### ISSUE THREAD

**Issue by Avnior** [UniversalLP/VanillaAutomation#34]
I'm trying to use a redstone clock, but when I try to set it to the right delay, it sets it to something else when I exit out of the GUI.

Also, as a side note, I wish the delay would go over 1000 ticks...

**Comment by Avnior** [comment]
Figured it out... It can only go up to 127 ticks... that means that the variable isn't long enough to store values larger than 127... any higher, then it starts to do odd things...

**Comment by univrsal** [comment]
I'll look into it, but it might take some time since I'm currently busy with other stuff

**Comment by Mielton** [comment]
você ainda meche no mod? se sim, você ainda vai tentar corrigir o relogio?

**Comment by univrsal** [comment]
I do not speak Portuguese, but if google translated correctly you asked whether I'm still working on this mod and if I'm going to fix this.
Well I haven't had much time in the past and I'm really busy with other projects, but I guess I'll take some time right now to fix this

**Comment by univrsal** [comment]
Alright, it's fixed.
Also the maximum value for delay and pulse length are now configurable.

**Comment by Mielton** [comment]
Obrigado!!! Gostei muito do seu mod, espero que continue criando!!
