### ISSUE TITLE
Filtered Hopper Crash

### ISSUE THREAD

**Issue by davqvist** [UniversalLP/VanillaAutomation#35]
See https://github.com/davqvist/Exoria/issues/280

I couldn't replicate myself, but maybe the crash log will help you figure out what the problem is.

Forge 2705
VA 1.5.2

**Comment by univrsal** [comment]
Sorry, that I'm getting back to you so late.
I've looked into this and the method that crashed is part of vanilla Minecraft and since I can't replicate it I don't really know what to do.
If this persists feel free to tell me
