### ISSUE TITLE
How to brake blocks with the dispenser

### ISSUE THREAD

**Issue by Geelik** [UniversalLP/VanillaAutomation#36]
Hey,

I use the 1.12.2 version and i can"t figure out how to brake blocks. i hear the sound that it use the tool but it doesn't brake the block in front.

Sorry for the broken english and if you need more info just ask.

**Comment by univrsal** [comment]
I don't know what's causing the problems for you, but putting tools in a dispenser should be enough

**Comment by Geelik** [comment]
I was using other mods, so i reinstalled all one by one starting with VA. Did not found any conflict but now it works. I don't understand why it didn't before. Sorry for wasting yor time.

EDIT : i found a conflict with TallGates mod. I removed it so no problem now.
EDIT 2 : in fact it stop working randomly, restarting minecraft make it work again.
Have a nice day.

**Comment by Geelik** [comment]
Ok finally i found what causes the issue. If you switch world without relaunching minecraft it stop working. Don't know if you gonna fix this, but i hope it will help you if you do.

**Comment by univrsal** [comment]
I found the issue. The fake player which breaks the block, didn't move to the new world after leaving and rejoining. It's fixed now and I'll put it up on curse
