### ISSUE TITLE
Mod Items not working in dispenser

### ISSUE THREAD

**Issue by darklordwonton** [UniversalLP/VanillaAutomation#7]
Tools and Swords added by mods don't work in the dispenser (tested with mithril pickaxe from base metals)

**Comment by univrsal** [comment]
That's because of the way the dispenser registry works. I have to register every tool manually. So I can not possibly add support for every tool from every mod. Does the pickaxe do anything special that the vanilla tools can't do?

**Comment by darklordwonton** [comment]
Since it only needs to register everything once per load would it be possible to loop through every registered item and register every item that extends the tool class to the tool dispenser event, every item that extends the sword class to the attack dispenser event, same for shears, etc.

Would that be possible or would it create too much lag?

**Comment by univrsal** [comment]
There you go. It'll register everything that is an instance of either the ItemTool or ItemSword class.
I'll make a release later

**Comment by darklordwonton** [comment]
Awesome
