### ISSUE TITLE
3 Suggestions for even more better automation

### ISSUE THREAD

**Issue by GrzechuGrek** [UniversalLP/VanillaAutomation#8]
1. I suggest you to add possibility to set redstone on vertical wall(and ceiling) in vertically and horizontally way if you will can do it.
2. Special crafting table/machine with crafting grid, 9-12 slots for items(ingredients) and one slot for crafted items. For each redstone signal tick, it'll do craft item for one time. It can be connected with hoppers on side or top to supply ingredients slots and bottom, to pull out crafted items.
3. Redstone clock in a block or half-block. It can be setting it frequency of redstone pulse(for example 0.5, 1, 2, 4 seconds) with PPM, and power with redstone to stop pulsing.

**Comment by univrsal** [comment]
Thanks,
I'll look into your suggestions and see which ones are easy to implement, when I get the time!

**Comment by brisingraerowing** [comment]
@GrzechuGrek 

For the first point you may want to look at [The Redstone Paste Mod](https://minecraft.curseforge.com/projects/redstone-paste), as it does exactly that (and adds in repeaters and comparators that can stick to walls and ceilings as well).

**Comment by univrsal** [comment]
I added the redstone clock. I'll leave the crafting table out for now
